site_name: AWS SOP 手冊
site_description: 以 Markdown 撰寫的 AWS 作業標準與流程
repo_url: https://github.com/Grezn/aws-sop

theme:
  name: material
  language: zh
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.suggest
    - toc.integrate

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - attr_list

nav:
  - 首頁: index.md
  - 03 網路 Network:
      - ALB / NLB 指南: 03-network/nlb-alb-guideline.md
  - 04 維運 Operations:
      - EC2 維護 SOP: 04-operations/ec2-maintenance.md
      - RDS 備份與還原: 04-operations/rds-backup-restore.md
      - S3 生命週期與封存: 04-operations/s3-lifecycle-archive.md
      - ASG 滾動更新: 04-operations/asg-rolling-update.md
  - 05 備援與演練 DR:
      - DR Runbook: 05-dr/dr-runbook.md
  - 參考 / 模板:
      - SOP 通用模板: _templates/sop-template.md
  - 操作手冊: 操作手冊.md
