site_name: AWS SOP 手冊
site_description: 以 Markdown 撰寫的 AWS 作業標準與流程
repo_url: https://github.com/Grezn/aws-sop

theme:
  name: material
  language: zh
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.suggest

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - attr_list

nav:
  - 首頁: index.md
  - 01 基礎 Foundation:
      - 帳號與組織結構: 01-foundation/account-structure.md
  - 02 安全 Security:
      - IAM 基線: 02-security/iam-baseline.md
  - 03 網路 Network:
      - VPC 標準: 03-network/vpc-standard.md
  - 04 維運 Operations:
      - EC2 維護 SOP: 04-operations/ec2-maintenance.md
